export type AcronymCategory =
  | "Fiscal"
  | "Comércio exterior"
  | "Logística"
  | "Financeiro"
  | "Marketing"
  | "Catálogo"
  | "Tecnologia"
  | "Dados cadastrais";

export type AcronymEntry = {
  acronym: string;
  meaning: string;
  category: AcronymCategory;
  explanation: string;
  appearsIn: string[];
  related?: string[];
};

export const ACRONYM_CATEGORIES: AcronymCategory[] = [
  "Fiscal",
  "Comércio exterior",
  "Logística",
  "Financeiro",
  "Marketing",
  "Catálogo",
  "Tecnologia",
  "Dados cadastrais",
];

export const ACRONYMS: AcronymEntry[] = [
  {
    acronym: "A1",
    meaning: "Certificado digital A1",
    category: "Fiscal",
    explanation: "Certificado digital em arquivo, usado para assinar documentos fiscais e acessar serviços oficiais quando autorizado.",
    appearsIn: ["Fiscal e Tributário", "Certificados digitais", "SEFAZ"],
    related: ["A3", "SEFAZ", "NF-e"],
  },
  {
    acronym: "A3",
    meaning: "Certificado digital A3",
    category: "Fiscal",
    explanation: "Certificado em cartão, token ou mídia física. Exige dispositivo e senha para uso operacional.",
    appearsIn: ["Fiscal e Tributário", "Certificados digitais"],
    related: ["A1", "SEFAZ"],
  },
  {
    acronym: "ANVISA",
    meaning: "Agência Nacional de Vigilância Sanitária",
    category: "Fiscal",
    explanation: "Órgão regulador relevante para cosméticos, ingredientes, rotulagem e conformidade sanitária.",
    appearsIn: ["Produtos e conformidade", "Comércio exterior", "Fiscal"],
  },
  {
    acronym: "API",
    meaning: "Interface de programação de aplicações",
    category: "Tecnologia",
    explanation: "Canal técnico usado para conectar a Flora a serviços externos como Resend, Stripe, transportadoras, marketplaces e órgãos oficiais.",
    appearsIn: ["Canais", "Integrações", "Marketing", "Logística", "Fiscal"],
  },
  {
    acronym: "B2B",
    meaning: "Empresa para empresa",
    category: "Financeiro",
    explanation: "Modelo de venda para empresas, lojas, clínicas, hotéis, distribuidores ou parceiros comerciais.",
    appearsIn: ["Financeiro", "Marketing", "Propostas comerciais"],
  },
  {
    acronym: "B2C",
    meaning: "Empresa para consumidor",
    category: "Financeiro",
    explanation: "Modelo de venda direta da Flora para o cliente final no site público.",
    appearsIn: ["Vendas", "Financeiro", "Storefront"],
  },
  {
    acronym: "BRL",
    meaning: "Real brasileiro",
    category: "Financeiro",
    explanation: "Moeda padrão usada nos preços, pedidos, relatórios, contabilidade e simulações nacionais.",
    appearsIn: ["Vendas", "Catálogo", "Financeiro", "Contabilidade"],
  },
  {
    acronym: "CAF",
    meaning: "Código de autorização de faturamento",
    category: "Fiscal",
    explanation: "Referência operacional usada em alguns fluxos fiscais ou autorizadores. Quando aparecer, deve ser conferida com o provedor fiscal adotado.",
    appearsIn: ["Fiscal", "Auditoria"],
  },
  {
    acronym: "CBSA",
    meaning: "Canada Border Services Agency",
    category: "Comércio exterior",
    explanation: "Agência de fronteira do Canadá, usada como fonte para regras, tarifas e processos de importação canadenses.",
    appearsIn: ["Comércio Exterior", "Jurisdições", "Tarifas aduaneiras"],
  },
  {
    acronym: "CEST",
    meaning: "Código Especificador da Substituição Tributária",
    category: "Fiscal",
    explanation: "Código fiscal brasileiro usado para identificar mercadorias sujeitas à substituição tributária.",
    appearsIn: ["Catálogo", "Fiscal", "Regras tributárias"],
    related: ["NCM", "ICMS-ST"],
  },
  {
    acronym: "CEP",
    meaning: "Código de Endereçamento Postal",
    category: "Dados cadastrais",
    explanation: "Código postal usado para endereço do cliente, cálculo de frete, entrega, rastreamento e dados fiscais.",
    appearsIn: ["Checkout", "Conta do cliente", "Pedidos", "Logística"],
  },
  {
    acronym: "CFOP",
    meaning: "Código Fiscal de Operações e Prestações",
    category: "Fiscal",
    explanation: "Código que classifica a natureza fiscal da operação, como venda, devolução, remessa, entrada ou exportação.",
    appearsIn: ["Notas fiscais", "Pedidos", "Comércio exterior"],
    related: ["NF-e", "NCM"],
  },
  {
    acronym: "CIF",
    meaning: "Cost, Insurance and Freight",
    category: "Comércio exterior",
    explanation: "Incoterm em que o vendedor assume custo, seguro e frete até o porto de destino indicado.",
    appearsIn: ["Comércio Exterior", "Incoterms", "Frete internacional"],
    related: ["FOB", "DAP", "DDP"],
  },
  {
    acronym: "CIP",
    meaning: "Carriage and Insurance Paid To",
    category: "Comércio exterior",
    explanation: "Incoterm em que o vendedor paga transporte e seguro até o local combinado.",
    appearsIn: ["Comércio Exterior", "Incoterms"],
  },
  {
    acronym: "CNPJ",
    meaning: "Cadastro Nacional da Pessoa Jurídica",
    category: "Dados cadastrais",
    explanation: "Identificação fiscal de empresas no Brasil.",
    appearsIn: ["Clientes", "Config fiscal", "Fiscal", "Orçamentos"],
  },
  {
    acronym: "COFINS",
    meaning: "Contribuição para o Financiamento da Seguridade Social",
    category: "Fiscal",
    explanation: "Tributo federal brasileiro que pode compor apurações, guias, cálculo de margem e obrigações contábeis.",
    appearsIn: ["Fiscal", "Contabilidade", "Financeiro"],
  },
  {
    acronym: "CPF",
    meaning: "Cadastro de Pessoas Físicas",
    category: "Dados cadastrais",
    explanation: "Identificação fiscal de pessoa física no Brasil.",
    appearsIn: ["Conta do cliente", "Pedidos", "Fiscal", "Clientes"],
  },
  {
    acronym: "CRM",
    meaning: "Gestão de relacionamento com clientes",
    category: "Marketing",
    explanation: "Área usada para relacionamento, histórico, segmentação, atendimento, campanhas e pós-venda.",
    appearsIn: ["Backoffice", "Clientes", "Marketing", "Inbox"],
  },
  {
    acronym: "CSLL",
    meaning: "Contribuição Social sobre o Lucro Líquido",
    category: "Fiscal",
    explanation: "Tributo federal ligado ao resultado da empresa, usado em análises contábeis e fiscais.",
    appearsIn: ["Fiscal", "Contabilidade", "Financeiro"],
  },
  {
    acronym: "CSV",
    meaning: "Valores separados por vírgula",
    category: "Tecnologia",
    explanation: "Formato de planilha simples usado para exportação e importação de dados.",
    appearsIn: ["Relatórios", "Catálogo", "Financeiro", "Marketing"],
  },
  {
    acronym: "DANFE",
    meaning: "Documento Auxiliar da Nota Fiscal Eletrônica",
    category: "Fiscal",
    explanation: "Representação imprimível da NF-e. Não substitui o XML autorizado, mas acompanha a operação.",
    appearsIn: ["Notas fiscais", "Cofre fiscal", "Logística"],
    related: ["NF-e", "XML"],
  },
  {
    acronym: "DAP",
    meaning: "Delivered At Place",
    category: "Comércio exterior",
    explanation: "Incoterm em que a Flora entrega no local combinado, mas o comprador normalmente assume importação, tributos e desembaraço no destino.",
    appearsIn: ["Comércio Exterior", "Incoterms", "Landed cost"],
    related: ["DDP", "EXW", "CIF"],
  },
  {
    acronym: "DARF",
    meaning: "Documento de Arrecadação de Receitas Federais",
    category: "Fiscal",
    explanation: "Guia usada para pagar tributos federais, inclusive em fluxos como DCTFWeb quando aplicável.",
    appearsIn: ["Guias e pagamentos", "Cofre fiscal", "Contabilidade"],
    related: ["DCTFWeb", "MIT"],
  },
  {
    acronym: "DAS",
    meaning: "Documento de Arrecadação do Simples Nacional",
    category: "Fiscal",
    explanation: "Guia mensal do Simples Nacional, quando a empresa está nesse regime.",
    appearsIn: ["Guias e pagamentos", "Regime fiscal", "Contabilidade"],
  },
  {
    acronym: "DCTFWeb",
    meaning: "Declaração de Débitos e Créditos Tributários Federais Web",
    category: "Fiscal",
    explanation: "Sistema/declaração federal usado para confessar débitos previdenciários e tributos relacionados, gerando guia quando aplicável.",
    appearsIn: ["Fiscal", "Guias e pagamentos", "Conexão Governo", "Cofre fiscal"],
    related: ["DARF", "MIT", "EFD-Reinf"],
  },
  {
    acronym: "DDD",
    meaning: "Discagem Direta a Distância",
    category: "Dados cadastrais",
    explanation: "Código de área do telefone, necessário para contato, WhatsApp, SMS e rastreamento.",
    appearsIn: ["Clientes", "Conta do cliente", "Inbox", "Pedidos"],
  },
  {
    acronym: "DDP",
    meaning: "Delivered Duty Paid",
    category: "Comércio exterior",
    explanation: "Incoterm em que a Flora assume entrega no destino com tributos de importação pagos ou provisionados.",
    appearsIn: ["Comércio Exterior", "Incoterms", "Landed cost"],
    related: ["DAP", "VAT", "GST"],
  },
  {
    acronym: "DIFAL",
    meaning: "Diferencial de Alíquota do ICMS",
    category: "Fiscal",
    explanation: "Diferença de ICMS entre estados em operações interestaduais, quando aplicável.",
    appearsIn: ["Fiscal", "Regras tributárias", "Guias"],
  },
  {
    acronym: "DOC",
    meaning: "Documento de Ordem de Crédito",
    category: "Financeiro",
    explanation: "Modalidade bancária antiga ainda citada em alguns cadastros para reembolsos ou dados financeiros.",
    appearsIn: ["Conta do cliente", "Financeiro"],
    related: ["TED", "PIX"],
  },
  {
    acronym: "DU-E",
    meaning: "Declaração Única de Exportação",
    category: "Comércio exterior",
    explanation: "Documento brasileiro de exportação no Portal Único Siscomex.",
    appearsIn: ["Comércio Exterior", "Documentos internacionais", "Portal Único"],
    related: ["LPCO", "NF-e"],
  },
  {
    acronym: "EAN",
    meaning: "European Article Number",
    category: "Catálogo",
    explanation: "Código de barras global de produto, hoje tratado dentro do padrão GTIN.",
    appearsIn: ["Catálogo", "Etiquetas", "Marketplaces"],
    related: ["GTIN", "SKU"],
  },
  {
    acronym: "ECF",
    meaning: "Escrituração Contábil Fiscal",
    category: "Fiscal",
    explanation: "Obrigação acessória fiscal ligada à apuração de IRPJ e CSLL.",
    appearsIn: ["Fiscal", "Contabilidade", "Agenda fiscal"],
  },
  {
    acronym: "EFD",
    meaning: "Escrituração Fiscal Digital",
    category: "Fiscal",
    explanation: "Família de escriturações digitais do SPED, como EFD ICMS/IPI e EFD-Reinf.",
    appearsIn: ["Fiscal", "Apuração e escriturações"],
    related: ["SPED", "EFD-Reinf"],
  },
  {
    acronym: "EFD-Reinf",
    meaning: "Escrituração Fiscal Digital de Retenções e Outras Informações Fiscais",
    category: "Fiscal",
    explanation: "Obrigação federal que pode alimentar DCTFWeb e controles trabalhistas/tributários.",
    appearsIn: ["Fiscal", "Conexão Governo", "Guias"],
    related: ["DCTFWeb", "MIT"],
  },
  {
    acronym: "ERP",
    meaning: "Planejamento de recursos empresariais",
    category: "Tecnologia",
    explanation: "Sistema integrado de gestão para vendas, estoque, fiscal, financeiro, logística e operação.",
    appearsIn: ["Backoffice", "Operações", "Financeiro", "Fiscal"],
  },
  {
    acronym: "EORI",
    meaning: "Economic Operators Registration and Identification",
    category: "Comércio exterior",
    explanation: "Registro europeu para operadores econômicos em importações e exportações.",
    appearsIn: ["Comércio Exterior", "Registros fiscais"],
    related: ["IOSS", "OSS", "VAT"],
  },
  {
    acronym: "EXW",
    meaning: "Ex Works",
    category: "Comércio exterior",
    explanation: "Incoterm em que o comprador assume quase todos os custos e riscos a partir do local de retirada.",
    appearsIn: ["Comércio Exterior", "Incoterms"],
  },
  {
    acronym: "FCA",
    meaning: "Free Carrier",
    category: "Comércio exterior",
    explanation: "Incoterm em que a Flora entrega a mercadoria ao transportador indicado em local combinado.",
    appearsIn: ["Comércio Exterior", "Incoterms"],
  },
  {
    acronym: "FCP",
    meaning: "Fundo de Combate à Pobreza",
    category: "Fiscal",
    explanation: "Adicional de ICMS cobrado em alguns estados e operações.",
    appearsIn: ["Fiscal", "Regras tributárias", "Guias"],
  },
  {
    acronym: "FGTS",
    meaning: "Fundo de Garantia do Tempo de Serviço",
    category: "Fiscal",
    explanation: "Obrigação trabalhista relacionada à folha, vencimentos e guias.",
    appearsIn: ["Fiscal", "Guias", "Conexão Governo"],
  },
  {
    acronym: "FOB",
    meaning: "Free On Board",
    category: "Comércio exterior",
    explanation: "Incoterm em que o vendedor entrega a mercadoria a bordo do navio; a partir daí o comprador assume custos e riscos principais.",
    appearsIn: ["Comércio Exterior", "Incoterms"],
  },
  {
    acronym: "GPS",
    meaning: "Sistema de Posicionamento Global",
    category: "Logística",
    explanation: "Usado no checkout para sugerir endereço ou CEP por localização, quando o cliente autoriza.",
    appearsIn: ["Checkout", "Logística"],
  },
  {
    acronym: "GST",
    meaning: "Goods and Services Tax",
    category: "Comércio exterior",
    explanation: "Imposto sobre bens e serviços usado em países como Canadá, Austrália e outros destinos.",
    appearsIn: ["Comércio Exterior", "IVA, VAT, GST e Sales Tax"],
    related: ["VAT", "Sales Tax"],
  },
  {
    acronym: "GTIN",
    meaning: "Global Trade Item Number",
    category: "Catálogo",
    explanation: "Identificador global de item comercial usado em códigos de barras e marketplaces.",
    appearsIn: ["Catálogo", "Etiquetas", "Marketplaces"],
    related: ["EAN", "SKU"],
  },
  {
    acronym: "HTML",
    meaning: "Linguagem de marcação de hipertexto",
    category: "Tecnologia",
    explanation: "Formato usado em páginas públicas, e-mails e blocos visuais.",
    appearsIn: ["CMS", "Marketing", "Templates"],
  },
  {
    acronym: "HS Code",
    meaning: "Harmonized System Code",
    category: "Comércio exterior",
    explanation: "Código internacional de classificação de mercadorias usado como base para tarifas e regras aduaneiras.",
    appearsIn: ["Comércio Exterior", "Classificação fiscal"],
    related: ["NCM", "HTS", "TARIC"],
  },
  {
    acronym: "HTS",
    meaning: "Harmonized Tariff Schedule",
    category: "Comércio exterior",
    explanation: "Tabela tarifária dos Estados Unidos baseada no sistema harmonizado.",
    appearsIn: ["Comércio Exterior", "Tarifas aduaneiras"],
    related: ["HS Code"],
  },
  {
    acronym: "IBGE",
    meaning: "Instituto Brasileiro de Geografia e Estatística",
    category: "Dados cadastrais",
    explanation: "Fonte de códigos de municípios e dados territoriais usados em cadastros fiscais e endereços.",
    appearsIn: ["Fiscal", "Clientes", "Endereços"],
  },
  {
    acronym: "ICMS",
    meaning: "Imposto sobre Circulação de Mercadorias e Serviços",
    category: "Fiscal",
    explanation: "Tributo estadual brasileiro que incide sobre circulação de mercadorias e alguns serviços.",
    appearsIn: ["Fiscal", "Guias", "Regras tributárias"],
    related: ["ICMS-ST", "DIFAL", "FCP"],
  },
  {
    acronym: "ICMS-ST",
    meaning: "ICMS por substituição tributária",
    category: "Fiscal",
    explanation: "Regime em que a responsabilidade pelo recolhimento do ICMS é atribuída a outro elo da cadeia.",
    appearsIn: ["Fiscal", "Regras tributárias"],
    related: ["ICMS", "CEST"],
  },
  {
    acronym: "INCI",
    meaning: "International Nomenclature Cosmetic Ingredient",
    category: "Comércio exterior",
    explanation: "Nomenclatura internacional de ingredientes cosméticos, importante para rotulagem e conformidade.",
    appearsIn: ["Produtos e conformidade", "Catálogo", "Comércio exterior"],
  },
  {
    acronym: "INSS",
    meaning: "Instituto Nacional do Seguro Social",
    category: "Fiscal",
    explanation: "Órgão e contribuição previdenciária usados em folha, guias e obrigações.",
    appearsIn: ["Fiscal", "Guias", "Contabilidade"],
  },
  {
    acronym: "IPI",
    meaning: "Imposto sobre Produtos Industrializados",
    category: "Fiscal",
    explanation: "Tributo federal incidente sobre produtos industrializados, quando aplicável.",
    appearsIn: ["Fiscal", "Regras tributárias", "Produtos"],
  },
  {
    acronym: "IRPJ",
    meaning: "Imposto de Renda da Pessoa Jurídica",
    category: "Fiscal",
    explanation: "Tributo federal sobre o lucro ou base presumida da empresa.",
    appearsIn: ["Fiscal", "Contabilidade"],
    related: ["CSLL"],
  },
  {
    acronym: "ISS",
    meaning: "Imposto sobre Serviços",
    category: "Fiscal",
    explanation: "Tributo municipal aplicado a prestação de serviços, incluindo NFS-e quando houver serviço tributável.",
    appearsIn: ["Fiscal", "Guias", "NFS-e"],
  },
  {
    acronym: "IOSS",
    meaning: "Import One-Stop Shop",
    category: "Comércio exterior",
    explanation: "Regime europeu para recolhimento de VAT em vendas importadas de baixo valor ao consumidor.",
    appearsIn: ["Comércio Exterior", "Registros fiscais"],
    related: ["VAT", "OSS", "EORI"],
  },
  {
    acronym: "IVA",
    meaning: "Imposto sobre Valor Agregado",
    category: "Comércio exterior",
    explanation: "Termo em português para imposto de valor agregado, equivalente conceitual ao VAT em muitos países.",
    appearsIn: ["Comércio Exterior", "IVA, VAT, GST e Sales Tax"],
    related: ["VAT", "GST"],
  },
  {
    acronym: "JSON",
    meaning: "JavaScript Object Notation",
    category: "Tecnologia",
    explanation: "Formato estruturado de dados usado em integrações, logs e exportações técnicas.",
    appearsIn: ["Integrações", "Logs", "Relatórios"],
  },
  {
    acronym: "KPI",
    meaning: "Indicador-chave de desempenho",
    category: "Financeiro",
    explanation: "Métrica usada para acompanhar resultado operacional, financeiro, marketing e vendas.",
    appearsIn: ["Dashboard", "Marketing", "Financeiro", "Contabilidade"],
  },
  {
    acronym: "LGPD",
    meaning: "Lei Geral de Proteção de Dados",
    category: "Marketing",
    explanation: "Lei brasileira de proteção de dados pessoais. Orienta consentimentos, preferências e uso de dados dos clientes.",
    appearsIn: ["Marketing", "Consentimentos", "Conta do cliente"],
  },
  {
    acronym: "LPco",
    meaning: "Licenças, Permissões, Certificados e Outros documentos",
    category: "Comércio exterior",
    explanation: "Módulo do Portal Único usado para controles administrativos em importação e exportação. Também aparece como LPCO.",
    appearsIn: ["Comércio Exterior", "DU-E", "Documentos internacionais"],
    related: ["LPCO", "DU-E"],
  },
  {
    acronym: "LPCO",
    meaning: "Licenças, Permissões, Certificados e Outros documentos",
    category: "Comércio exterior",
    explanation: "Grafia em caixa alta de LPco; usada para documentos e controles administrativos no Portal Único.",
    appearsIn: ["Comércio Exterior", "DU-E", "Portal Único"],
    related: ["LPco", "DU-E"],
  },
  {
    acronym: "LWA",
    meaning: "Login with Amazon",
    category: "Tecnologia",
    explanation: "Autenticação usada em integrações com Amazon Seller/SP-API.",
    appearsIn: ["Configurações", "Integrações", "Marketplaces"],
    related: ["SP-API"],
  },
  {
    acronym: "MEI",
    meaning: "Microempreendedor Individual",
    category: "Fiscal",
    explanation: "Regime simplificado para pequenos empreendedores, com obrigações e limites específicos.",
    appearsIn: ["Regime fiscal", "Fiscal", "Contabilidade"],
    related: ["DAS"],
  },
  {
    acronym: "MIT",
    meaning: "Módulo de Inclusão de Tributos",
    category: "Fiscal",
    explanation: "Sistema usado para incluir débitos tributários federais e compor apurações/guias, quando aplicável.",
    appearsIn: ["Conexão Governo", "Guias", "Fiscal"],
    related: ["DCTFWeb", "DARF"],
  },
  {
    acronym: "NCM",
    meaning: "Nomenclatura Comum do Mercosul",
    category: "Fiscal",
    explanation: "Código fiscal/classificatório de mercadorias no Brasil e Mercosul, usado em NF-e, impostos, exportação e marketplaces.",
    appearsIn: ["Catálogo", "Fiscal", "Comércio Exterior"],
    related: ["HS Code", "CEST", "CFOP"],
  },
  {
    acronym: "NFC-e",
    meaning: "Nota Fiscal de Consumidor Eletrônica",
    category: "Fiscal",
    explanation: "Documento fiscal eletrônico usado em venda ao consumidor final presencial ou varejo, quando aplicável.",
    appearsIn: ["Notas fiscais", "Fiscal"],
  },
  {
    acronym: "NF-e",
    meaning: "Nota Fiscal Eletrônica",
    category: "Fiscal",
    explanation: "Documento fiscal eletrônico para venda, remessa, devolução, entrada, complemento, ajuste e exportação.",
    appearsIn: ["Notas fiscais", "Pedidos", "Logística", "Cofre fiscal"],
    related: ["DANFE", "XML", "SEFAZ"],
  },
  {
    acronym: "NFS-e",
    meaning: "Nota Fiscal de Serviço Eletrônica",
    category: "Fiscal",
    explanation: "Documento fiscal eletrônico para prestação de serviços, normalmente vinculado à prefeitura.",
    appearsIn: ["Notas fiscais", "Prefeitura / ISS"],
    related: ["ISS"],
  },
  {
    acronym: "NSU",
    meaning: "Número Sequencial Único",
    category: "Financeiro",
    explanation: "Identificador de transação usado por adquirentes, gateways e conciliação financeira.",
    appearsIn: ["Pedidos", "Financeiro", "Pagamentos"],
  },
  {
    acronym: "OSS",
    meaning: "One-Stop Shop",
    category: "Comércio exterior",
    explanation: "Regime europeu para declaração e pagamento de VAT em vendas dentro da União Europeia.",
    appearsIn: ["Comércio Exterior", "Registros fiscais"],
    related: ["IOSS", "VAT"],
  },
  {
    acronym: "PDF",
    meaning: "Portable Document Format",
    category: "Tecnologia",
    explanation: "Formato de documento usado para relatórios, etiquetas, guias, DANFE, propostas, comprovantes e exports.",
    appearsIn: ["Cofre fiscal", "Relatórios", "Logística", "Financeiro"],
  },
  {
    acronym: "PIS",
    meaning: "Programa de Integração Social",
    category: "Fiscal",
    explanation: "Tributo federal brasileiro que pode compor apurações e formação de preço.",
    appearsIn: ["Fiscal", "Contabilidade", "Financeiro"],
  },
  {
    acronym: "PIX",
    meaning: "Pagamento instantâneo brasileiro",
    category: "Financeiro",
    explanation: "Meio de pagamento instantâneo usado em checkout, reembolsos e dados financeiros.",
    appearsIn: ["Checkout", "Conta do cliente", "Pedidos", "Financeiro"],
  },
  {
    acronym: "PLP",
    meaning: "Pré-lista de postagem",
    category: "Logística",
    explanation: "Lista de postagem usada por alguns operadores logísticos para preparar remessas e etiquetas.",
    appearsIn: ["Logística", "Etiquetas", "Expedição"],
  },
  {
    acronym: "PN",
    meaning: "Part number",
    category: "Catálogo",
    explanation: "Código interno ou referência de peça/produto, usado quando o fornecedor ou canal trabalha com esse padrão.",
    appearsIn: ["Catálogo", "Produtos"],
  },
  {
    acronym: "QR Code",
    meaning: "Código de resposta rápida",
    category: "Logística",
    explanation: "Código visual usado em etiquetas, rastreamento, pagamentos, documentos e conferência.",
    appearsIn: ["Logística", "Etiquetas", "Fiscal"],
  },
  {
    acronym: "RBAC",
    meaning: "Controle de acesso baseado em papéis",
    category: "Tecnologia",
    explanation: "Modelo de permissões que define o que cada tipo de usuário pode ver e executar.",
    appearsIn: ["Configurações", "Segurança", "Plataforma"],
  },
  {
    acronym: "RLS",
    meaning: "Segurança em nível de linha",
    category: "Tecnologia",
    explanation: "Recurso do Supabase/Postgres que protege dados por tenant, usuário e permissão.",
    appearsIn: ["Supabase", "Banco de dados", "Segurança"],
  },
  {
    acronym: "ROI",
    meaning: "Retorno sobre investimento",
    category: "Marketing",
    explanation: "Métrica que compara resultado gerado com investimento feito em campanha, canal ou ação.",
    appearsIn: ["Marketing", "Financeiro", "Relatórios"],
  },
  {
    acronym: "SEFAZ",
    meaning: "Secretaria da Fazenda",
    category: "Fiscal",
    explanation: "Órgão estadual responsável por autorizar NF-e, eventos fiscais e validações tributárias.",
    appearsIn: ["Notas fiscais", "Config fiscal", "Eventos fiscais"],
    related: ["NF-e", "DANFE", "XML"],
  },
  {
    acronym: "SKU",
    meaning: "Stock Keeping Unit",
    category: "Catálogo",
    explanation: "Código interno de controle de produto/variante usado em estoque, etiquetas, pedidos, kits e marketplaces.",
    appearsIn: ["Catálogo", "Estoque", "Etiquetas", "Pedidos"],
    related: ["GTIN", "EAN"],
  },
  {
    acronym: "SLA",
    meaning: "Acordo de nível de serviço",
    category: "Logística",
    explanation: "Prazo ou compromisso operacional para entrega, resposta, expedição ou atendimento.",
    appearsIn: ["Logística", "Atendimento", "Comércio exterior"],
  },
  {
    acronym: "SMS",
    meaning: "Mensagem curta de texto",
    category: "Marketing",
    explanation: "Canal de comunicação para avisos, rastreamento, campanhas e recuperação, quando houver provedor oficial conectado.",
    appearsIn: ["Marketing", "Inbox", "Canais"],
  },
  {
    acronym: "SP-API",
    meaning: "Selling Partner API",
    category: "Tecnologia",
    explanation: "API da Amazon para integração com vendedores, catálogo, pedidos e relatórios.",
    appearsIn: ["Configurações", "Marketplaces", "Amazon"],
    related: ["LWA"],
  },
  {
    acronym: "SPED",
    meaning: "Sistema Público de Escrituração Digital",
    category: "Fiscal",
    explanation: "Ecossistema brasileiro de escrituração digital fiscal e contábil.",
    appearsIn: ["Fiscal", "Apuração e escriturações"],
    related: ["EFD", "ECF"],
  },
  {
    acronym: "TARIC",
    meaning: "Tarifa Integrada da União Europeia",
    category: "Comércio exterior",
    explanation: "Base tarifária europeia usada para impostos, restrições e classificação no comércio exterior.",
    appearsIn: ["Comércio Exterior", "Tarifas aduaneiras"],
    related: ["HS Code"],
  },
  {
    acronym: "TED",
    meaning: "Transferência Eletrônica Disponível",
    category: "Financeiro",
    explanation: "Modalidade bancária citada em cadastros financeiros e reembolsos.",
    appearsIn: ["Conta do cliente", "Financeiro"],
    related: ["DOC", "PIX"],
  },
  {
    acronym: "UF",
    meaning: "Unidade Federativa",
    category: "Dados cadastrais",
    explanation: "Estado brasileiro usado em endereço, frete, impostos, DIFAL, clientes e pedidos.",
    appearsIn: ["Checkout", "Clientes", "Fiscal", "Logística"],
  },
  {
    acronym: "UKGT",
    meaning: "UK Global Tariff",
    category: "Comércio exterior",
    explanation: "Tabela tarifária do Reino Unido para importação de mercadorias.",
    appearsIn: ["Comércio Exterior", "Tarifas aduaneiras"],
  },
  {
    acronym: "URL",
    meaning: "Localizador uniforme de recurso",
    category: "Tecnologia",
    explanation: "Endereço de página, API, arquivo, checkout, rastreamento, callback ou webhook.",
    appearsIn: ["CMS", "Integrações", "Marketing", "Canais"],
  },
  {
    acronym: "UTM",
    meaning: "Urchin Tracking Module",
    category: "Marketing",
    explanation: "Parâmetros usados em links para identificar origem, mídia, campanha, termo e conteúdo.",
    appearsIn: ["Marketing", "Campanhas", "Atribuição"],
  },
  {
    acronym: "VAT",
    meaning: "Value Added Tax",
    category: "Comércio exterior",
    explanation: "Imposto sobre valor agregado usado em diversos países. Em português, é o IVA.",
    appearsIn: ["Comércio Exterior", "IVA, VAT, GST e Sales Tax"],
    related: ["IVA", "GST", "IOSS", "OSS"],
  },
  {
    acronym: "XML",
    meaning: "Extensible Markup Language",
    category: "Tecnologia",
    explanation: "Formato estruturado oficial da NF-e e de outros documentos fiscais. O XML autorizado é o documento fiscal principal.",
    appearsIn: ["Notas fiscais", "Cofre fiscal", "SEFAZ"],
    related: ["NF-e", "DANFE"],
  },
  {
    acronym: "XLSX",
    meaning: "Planilha do Microsoft Excel",
    category: "Tecnologia",
    explanation: "Formato de planilha usado em importações e exportações de catálogo, relatórios e controles.",
    appearsIn: ["Catálogo", "Relatórios", "Financeiro", "Marketing"],
  },
  {
    acronym: "ZPL",
    meaning: "Zebra Programming Language",
    category: "Logística",
    explanation: "Linguagem de impressão usada por impressoras térmicas Zebra e compatíveis para etiquetas.",
    appearsIn: ["Logística", "Etiquetas", "Marketplaces"],
  },
];
